### ISSUE TITLE
 No module named 'inference_core_nodes'

### ISSUE THREAD

**Issue by ariseshu** [LykosAI/ComfyUI-Inference-Core-Nodes#5]
Display error "File "D:\AI\ComfyUI_Full\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes-main\__init__.py", line 1, in &lt; module&gt;
from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

Cannot import D:\AI\ComfyUI_Full\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes-main module for custom nodes:  No module named 'inference_core_nodes' ", Excuse me, how can I solve this problem👧

**Comment by nothingness6** [comment]
> Display error "File "D:\AI\ComfyUI_Full\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes-main__init__.py", line 1, in < module> from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS ModuleNotFoundError: No module named 'inference_core_nodes'
> 
> Cannot import D:\AI\ComfyUI_Full\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes-main module for custom nodes: No module named 'inference_core_nodes' ", Excuse me, how can I solve this problem👧

I faced the same issue. Have you figured it out?

**Comment by ariseshu** [comment]
> > Display error "File "D:\AI\ComfyUI_Full\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes-main__init__.py", line 1, in < module> from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS ModuleNotFoundError: No module named 'inference_core_nodes'
> > Cannot import D:\AI\ComfyUI_Full\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes-main module for custom nodes: No module named 'inference_core_nodes' ", Excuse me, how can I solve this problem👧
> 
> I faced the same issue. Have you figured it out?

no

**Comment by lingfan** [comment]
ERROR: onnxruntime_gpu-1.17.1-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

python 3.11
onnxruntime_gpu-1.17.1-cp311-cp311-win_amd64.whl
.\python_embeded\python.exe -m pip install flit_core
.\python_embeded\python.exe ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\install.py

**Comment by ionite34** [comment]
This happens if the install script fails to complete successfully, can you try running the `install.py` script with the venv and see if there are any errors?

**Comment by ionite34** [comment]
> ERROR: onnxruntime_gpu-1.17.1-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
> 
> python 3.11 onnxruntime_gpu-1.17.1-cp311-cp311-win_amd64.whl .\python_embeded\python.exe -m pip install flit_core .\python_embeded\python.exe ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\install.py

Currently I have it installing the onnxruntime-gpu wheel for 3.10 since that's what Stability Matrix was using, will look to add a case for 3.11 as well. In the meantime, you can install manually by running via venv or embedded python in the ComfyUI-Inference-Core-Nodes folder:
```
-m pip install -e .
```
Then if you have the `onnxruntime_gpu-1.17.1-cp311-cp311-win_amd64.whl` wheel you can individually install that for gpu support.

**Comment by littletigerwolf** [comment]
Still has this error


Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes module for custom nodes: No module named 'inference_core_nodes'

**Comment by POWERFULMOVES** [comment]
Prestartup times for custom nodes:
   0.6 seconds: L:\Comfyui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 32529 MB
xformers version: 0.0.25.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Traceback (most recent call last):
  File "L:\Comfyui\ComfyUI\ComfyUI\nodes.py", line 1866, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "L:\Comfyui\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

**Comment by catlog66** [comment]
Still happening
Total VRAM 16379 MB, total RAM 32668 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V5.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.5)
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes module for custom nodes: No module named 'inference_core_nodes'
### Loading: ComfyUI-Inspire-Pack (V0.68.2)
### Loading: ComfyUI-Manager (V2.24.1)
### ComfyUI Revision: 2157 [89d0e9ab] | Released on '2024-05-02'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_IPAdapter_plus-6a411dcb2c6c3b91a3aac97adfb080a77ade7d38\\__init__.py'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-6a411dcb2c6c3b91a3aac97adfb080a77ade7d38 module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_IPAdapter_plus-6a411dcb2c6c3b91a3aac97adfb080a77ade7d38\\__init__.py'
[comfy_mtb] | INFO -> loaded 70 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

[rgthree] Loaded 37 fantastic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.
